
def count_divisors(k):
    sum = 0
    for i in range(1, k +1):
        if k % i == 0:
            sum += 1
    return sum

def create_triangle(max):
    triangle = 1
    counter = 2
    while count_divisors(triangle) < max :
        triangle += counter
        counter += 1    
    return triangle


def solution():
    print("The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 28 . We can see that 28 is the first triangle number to have over five divisors. What is the value of the first triangle number to have over N = five hundred divisors??\n\n")
    print("Enter N:\n")
    n = input()
    print("Answer:\n")
    print(create_triangle(int(n)))
