def solution_task002(N):
    fibonacci = [1, 2]
    sum = 0
    while True:
        if max(fibonacci) > int(N):
            fibonacci.remove(max(fibonacci))
            break
        fibonacci.sort()
        fibonacci.append(fibonacci[-1] + fibonacci[-2])    
    print(fibonacci)
    for x in fibonacci:
        if x %2 == 0:
            sum += x
    return sum


def task002_output():
    print("Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,the first 10 terms will be: \n 1,2,3,5,8,13,21,...\nBy considering the terms in the Fibonacci sequence whose values do not exceed N = four million, find the sum of the even-valued terms..\n\n")
    print("Enter N:\n")
    n = input()
    print("Answer:\n")
    print(solution_task002(n))
